apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-app-week2
  namespace: aluno-afonso
  labels:
    aluno: afonso
spec:
  rules:
  - host: app-afonso.aula.jac.bsb.br
    http:
      paths:
      - backend:
          service:
            name: service-app-week2
            port:
              number: 80
        path: /
        pathType: Prefix
