apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    aluno: afonso
  name: monitor-app-week
  namespace: aluno-afonso
spec:
  podMetricsEndpoints:
  - port: http
    interval: 10s
  selector:
    matchLabels:
      app: app-week
